INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLES) VALUES (1, 'TestUser', 'user@user.user', '12345678', 'ROLE_USER');
INSERT INTO USERS (ID, NAME, EMAIL, PASSWORD, ROLES) VALUES (2, 'TestAdmin', 'admin@admin.admin', 'adminadmin', 'ROLE_USER,ROLE_ADMIN');
