CREATE TABLE USERS
(
    ID       INT NOT NULL AUTO_INCREMENT,
    NAME     VARCHAR(100) DEFAULT NULL,
    EMAIL    VARCHAR(100) DEFAULT NULL,
    PASSWORD VARCHAR(100) DEFAULT NULL,
    ROLES    VARCHAR(100) DEFAULT NULL,
    PRIMARY KEY (ID)
);